name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make dir
      run: mkdir build
    - name: go in folder
      run: cd build
    - name: cmake
      run: cmake ..
    - name: cmake build
      run: cmake --build .
    - name: test
      run: ctest
   
      
